# Registry and rpository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: asserts
  cartVersion: "1.0.3"
  catalogueVersion: "1.0.2"
  dispatchVersion: "1.0.2"
  mongodbVersion: "1.0.1"
  mysqlVersion: "1.0"
  paymentVersion: "1.0.2"
  ratingsVersion: "1.0.1"
  shippingVersion: "1.0.5"
  userVersion: "1.0.3"
  webVersion: "1.0.1"
  pullPolicy: IfNotPresent

# Payment gateway URL
payment:
  gateway: null
  #gateway: https://www.paypal.com
  #gateway: https://www.worldpay.com

# Pod Security Policy
psp:
  enabled: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

# Storage class to use with redis statefulset.
redis:
  storageClassName: gp3

ocCreateRoute: false

rabbitmq:
  enableExporter: false