# Registry and rpository for Docker images
# Default is docker/robotshop/image:latest
image:
  repo: asserts
  cartVersion: "1.0.1"
  catalogueVersion: "1.0.1"
  dispatchVersion: "1.0.1"
  mongodbVersion: "1.0"
  mysqlVersion: "1.0"
  paymentVersion: "1.0.1"
  ratingsVersion: "1.0"
  shippingVersion: "1.0.1"
  userVersion: "1.0.1"
  webVersion: "1.0"
  pullPolicy: IfNotPresent

# Alternative payment gateway URL
# Default is https://www.paypal.com
payment:
  gateway: null
  #gateway: https://www.worldpay.com

# EUM configuration
# Provide your key and set the endpoint
eum:
  key: null
  url: https://eum-eu-west-1.instana.io
  #url: https://eum-us-west-2.instana.io

# Pod Security Policy
psp:
  enabled: false

# "special" Openshift. Set to true when deploying to any openshift flavour
openshift: false

# Storage class to use with redis statefulset.
redis:
  storageClassName: gp3

ocCreateRoute: false
