{{- if .Values.tracing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    service: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jaeger
  template:
    metadata:
      labels:
        service: jaeger
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      imagePullSecrets:
        - name: docker-hub
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.38
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPAN_STORAGE_TYPE
              value: "elasticsearch"
            - name: ES_SERVER_URLS
              value: "http://es-jaeger:9200"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - containerPort: 16686
            - containerPort: 5778
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 14250
            - containerPort: 14268
            - containerPort: 14269
            - containerPort: 9411
          resources:
            limits:
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 1024Mi
      restartPolicy: Always
{{- end }}
