{{- if .Values.tracing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: robot-shop
  labels:
    service: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      service: otel-collector
  template:
    metadata:
      labels:
        service: otel-collector
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      imagePullSecrets:
        - name: docker-hub
      containers:
        - name: otel-collector
          image: {{ .Values.image.repo }}/otel-collector:{{ .Values.image.otelcollectorVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: otlp
              containerPort: 4317
            - name: otlphttp
              containerPort: 4318
            - name: jaeger
              containerPort: 14250
            - name: jaeger-thrift
              containerPort: 14268
            - name: jaeger-http
              containerPort: 14278
            - name: otel-metrics
              containerPort: 8889
            - name: prom-metrics
              containerPort: 8888
            - name: http-metrics
              containerPort: 9465
          volumeMounts:
            - mountPath: /etc/asserts
              name: collector-config
          resources:
            limits:
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 1024Mi
      restartPolicy: Always
      volumes:
        - configMap:
            items:
            - key: collector-config.yaml
              path: collector-config.yaml
            name: collector-config
          name: collector-config
  {{- end }}
