apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    service: payment
    stage: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
      stage: prod
  template:
    metadata:
      labels:
        service: payment
        stage: prod
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      imagePullSecrets:
        - name: docker-hub      
      containers:
      - name: payment
        image: {{ .Values.image.repo }}/robot-shop-rs-payment:{{ .Values.image.paymentVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # agent networking access
        env:
          {{- if .Values.payment.failureHour }}
          - name: FAILURE_HOUR
            value: {{ .Values.payment.failureHour | quote }}
          {{- end }}
          {{- if .Values.payment.failureFromMinute }}
          - name: FAILURE_FROM_MINUTE
            value: {{ .Values.payment.failureFromMinute | quote }}
          {{- end }}
          {{- if .Values.payment.failureTillMinute }}
          - name: FAILURE_TILL_MINUTE
            value: {{ .Values.payment.failureTillMinute | quote }}
          {{- end }}
          {{- if .Values.payment.gateway }}
          - name: PAYMENT_GATEWAY
            value: {{ .Values.payment.gateway }}
          {{- end }}
          - name: JAEGER_HOST
            value: "http://jaeger.monitoring.svc.cluster.local:14268"
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: "http://jaeger.monitoring.svc.cluster.local:14250"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
