apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    service: user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: user
        image: {{ .Values.image.repo }}/rs-user:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          # agent networking access
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          {{ if .Values.appRedisConnection.host }}
          - name: REDIS_HOST
            value: {{ .Values.appRedisConnection.host | quote }}
          {{ end }}
          {{ if .Values.appRedisConnection.port }}
          - name: REDIS_PORT
            value: {{ .Values.appRedisConnection.port | quote }}
          {{ end }}
          {{ if .Values.appRedisConnection.db }}
          - name: REDIS_DB
            value: {{ .Values.appRedisConnection.db | quote }}
          {{ end }}
          {{ if .Values.appRedisConnection.sslCrt }}
          - name: REDIS_SSL_CRT
            value: {{ .Values.appRedisConnection.sslCrt | quote }}
          {{ end }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
